Class {
	#name : #ASTCInterpreterProxy,
	#superclass : #Object,
	#category : #'ASTC-Translation'
}

{ #category : #adding }
ASTCInterpreterProxy >> integerObjectOf: anInteger [
	<doNotGenerate>
	"dummy method for type inference and system checks"
	^1
]

{ #category : #adding }
ASTCInterpreterProxy >> pop: anInteger [
	<doNotGenerate>
	"dummy method for type inference and system checks"
	^1
]

{ #category : #adding }
ASTCInterpreterProxy >> push: anArg [
	<doNotGenerate>
	"dummy method for type inference and system checks"
	^1
]
