Class {
	#name : #ASTCInterpreterProxy,
	#superclass : #Object,
	#category : #'ASTC-Translation'
}

{ #category : #adding }
ASTCInterpreterProxy >> cCoerce: anOop to: aType [
	<doNotGenerate>
	"dummy method for type inference and system checks"
	^self
]

{ #category : #adding }
ASTCInterpreterProxy >> integerObjectOf: anInteger [
	<doNotGenerate>
	"dummy method for type inference and system checks"
	^self
]

{ #category : #adding }
ASTCInterpreterProxy >> pop: anInteger [
	<doNotGenerate>
	"dummy method for type inference and system checks"
	^self
]

{ #category : #adding }
ASTCInterpreterProxy >> push: anArg [
	<doNotGenerate>
	"dummy method for type inference and system checks"
	^self
]

{ #category : #adding }
ASTCInterpreterProxy >> pushInteger: anInteger [
	<doNotGenerate>
	"dummy method for type inference and system checks"
	^self
]

{ #category : #adding }
ASTCInterpreterProxy >> stackValue: anOffset [
	<doNotGenerate>
	"dummy method for type inference and system checks"
	^self
]
