Class {
	#name : #ASTCVisitor,
	#superclass : #Object,
	#category : #'ASTC-Gen-visitors'
}

{ #category : #visiting }
ASTCVisitor >> visitAbstractWhile: anAbstractWhile [
	
]

{ #category : #visiting }
ASTCVisitor >> visitBlock: aBlock [
	
]

{ #category : #visiting }
ASTCVisitor >> visitCompilationUnit: aCompilationUnit [
	
]

{ #category : #visiting }
ASTCVisitor >> visitDeclaration: aDeclaration [
	
]

{ #category : #visiting }
ASTCVisitor >> visitDeclarationStatement: aDeclarationStatement [
	
]

{ #category : #visiting }
ASTCVisitor >> visitDefinition: aDefinition [
	
]

{ #category : #visiting }
ASTCVisitor >> visitDoWhile: aDoWhile [
	
]

{ #category : #visiting }
ASTCVisitor >> visitExpression: anExpression [
	
]

{ #category : #visiting }
ASTCVisitor >> visitExpressionStatement: anExpressionStatement [
	
]

{ #category : #visiting }
ASTCVisitor >> visitFor: aFor [
	
]

{ #category : #visiting }
ASTCVisitor >> visitFunctionCall: aFunctionCall [
	
]

{ #category : #visiting }
ASTCVisitor >> visitFunctionDeclaration: aFunctionDeclaration [
	
]

{ #category : #visiting }
ASTCVisitor >> visitFunctionDefinition: aFunctionDefinition [
	
]

{ #category : #visiting }
ASTCVisitor >> visitIdentifier: anIdentifier [
	
]

{ #category : #visiting }
ASTCVisitor >> visitIf: anIf [
	
]

{ #category : #visiting }
ASTCVisitor >> visitLiteral: aLiteral [
	
]

{ #category : #visiting }
ASTCVisitor >> visitLoop: aLoop [
	
]

{ #category : #visiting }
ASTCVisitor >> visitNode: aNode [
	
]

{ #category : #visiting }
ASTCVisitor >> visitOperator: anOperator [
	
]

{ #category : #visiting }
ASTCVisitor >> visitProject: aProject [
	
]

{ #category : #visiting }
ASTCVisitor >> visitReturn: aReturn [
	
]

{ #category : #visiting }
ASTCVisitor >> visitStatement: aStatement [
	
]

{ #category : #visiting }
ASTCVisitor >> visitStructureDeclaration: aStructureDeclaration [
	
]

{ #category : #visiting }
ASTCVisitor >> visitStructureDefinition: aStructureDefinition [
	
]

{ #category : #visiting }
ASTCVisitor >> visitType: aType [
	
]

{ #category : #visiting }
ASTCVisitor >> visitVariableDeclaration: aVariableDeclaration [
	
]

{ #category : #visiting }
ASTCVisitor >> visitVariableDefinition: aVariableDefinition [
	
]

{ #category : #visiting }
ASTCVisitor >> visitWhile: aWhile [
	
]
