Class {
	#name : #ASTCVisitor,
	#superclass : #Object,
	#category : #'ASTC-Gen-visitor'
}

{ #category : #visiting }
ASTCVisitor >> visitASTCCompilationUnit: anASTCCompilationUnit [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCDeclaration: anASTCDeclaration [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCDefinition: anASTCDefinition [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCExpression: anASTCExpression [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCNode: anASTCNode [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCProject: anASTCProject [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCStatement: anASTCStatement [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCType: anASTCType [
]
