Class {
	#name : #ASTCVisitor,
	#superclass : #Object,
	#category : #'ASTC-Gen'
}

{ #category : #visiting }
ASTCVisitor >> visitASTCAbstractWhile: anASTCAbstractWhile [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCBlock: anASTCBlock [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCCompilationUnit: anASTCCompilationUnit [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCDeclaration: anASTCDeclaration [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCDeclarationStatement: anASTCDeclarationStatement [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCDefinition: anASTCDefinition [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCDoWhile: anASTCDoWhile [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCExpression: anASTCExpression [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCExpressionStatement: anASTCExpressionStatement [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCFor: anASTCFor [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCFunctionCall: anASTCFunctionCall [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCFunctionDeclaration: anASTCFunctionDeclaration [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCFunctionDefinition: anASTCFunctionDefinition [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCIdentifier: anASTCIdentifier [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCIf: anASTCIf [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCLiteral: anASTCLiteral [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCLoop: anASTCLoop [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCNode: anASTCNode [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCOperator: anASTCOperator [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCProject: anASTCProject [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCReturn: anASTCReturn [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCStatement: anASTCStatement [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCType: anASTCType [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCVariableDeclaration: anASTCVariableDeclaration [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCVariableDefinition: anASTCVariableDefinition [
]

{ #category : #visiting }
ASTCVisitor >> visitASTCWhile: anASTCWhile [
]
